version: 2

workflows:
  version: 2
  run_tests:
    jobs:
      - run_tests
  deploy:
    jobs:
      - dev_deploy:
         filters:
           branches:
             only:
               - main
      - prod_deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/

jobs:
  run_tests:
    docker:
      - image: circleci/ruby:2.7.2-node
        environment:
          TZ: "America/New_York"

      - image: circleci/postgres:11-alpine
        environment:
          TZ: "America/New_York"
          BUNDLER_VERSION: "2.0.1"
    steps:
      - checkout
      - run:
          command: |
            sudo gem update --system
            sudo gem install -f bundler --version 1.17.2
            sudo apt-get update
            sudo apt-get install postgresql-client
            sudo psql -c "create role funnelcake with createdb login password 'password';" -U postgres -h localhost
            sudo bundle install
            RAILS_ENV=test sudo bundle exec rake db:setup
            RAILS_ENV=test sudo bundle exec rake db:seed
            RAILS_ENV=test sudo bundle exec rake db:migrate
            SECRET_KEY_BASE=foo RAILS_ENV=test sudo bundle exec rails assets:precompile
            sudo bundle exec rubocop
            RAILS_ENV=test sudo bundle exec rspec
  dev_deploy:
    docker:
      - image: circleci/python:3.7.2
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "2f:37:66:17:11:ae:f9:0f:9e:52:98:41:fe:d0:0c:78"
            - "26:72:9f:6f:07:49:10:33:b0:de:a5:72:de:1c:6e:ff"
      - run:
          command: bash .circleci/deploy-dev.sh

  prod_deploy:
    docker:
      - image: circleci/python:3.7.2
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "2f:37:66:17:11:ae:f9:0f:9e:52:98:41:fe:d0:0c:78"
            - "26:72:9f:6f:07:49:10:33:b0:de:a5:72:de:1c:6e:ff"
      - run:
          command: bash .circleci/deploy-prod.sh
