version: 2

workflows:
  version: 2
  run_tests:
    jobs:
      - run_tests
  deploy:
    jobs:
      - dev_deploy:
         filters:
           branches:
             only:
               - main
      - prod_deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/

jobs:
  run_tests:
    docker:
      - image: cimg/ruby:2.7.2-node
        environment:
          TZ: "America/New_York"
          RAILS_ENV: test

      - image: cimg/postgres:11.13
        environment:
          RAILS_ENV: test
          TZ: "America/New_York"
    steps:
      - checkout
      - run:
          name: make sure we have the latest bundler
          command: |
            sudo gem update --system
            gem install -f bundler:2.1.4
      - run:
          name: bundle install w/ dependent libs
          command: |
            sudo apt-get --allow-releaseinfo-change update
            sudo apt-get update
            sudo apt-get install postgresql-client libsqlite3-dev
            bundle install --path vendor/bundle
      - run:
          name: Ruby Lint
          command: bundle exec rubocop
      - run:
          name: Set up db for run
          command: |
            sudo psql -c "create role funnelcake with createdb login password 'password';" -U postgres -h localhost
            bundle exec rake db:setup
            bundle exec rake db:seed
            bundle exec rake db:migrate
      - run:
          name: Run ruby tests
          command: bundle exec rspec
  dev_deploy:
    docker:
      - image: cimg/python:3.7.11
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "2f:37:66:17:11:ae:f9:0f:9e:52:98:41:fe:d0:0c:78"
            - "26:72:9f:6f:07:49:10:33:b0:de:a5:72:de:1c:6e:ff"
      - run:
          command: bash .circleci/deploy-dev.sh

  prod_deploy:
    docker:
      - image: cimg/python:3.7.11
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "2f:37:66:17:11:ae:f9:0f:9e:52:98:41:fe:d0:0c:78"
            - "26:72:9f:6f:07:49:10:33:b0:de:a5:72:de:1c:6e:ff"
      - run:
          command: bash .circleci/deploy-prod.sh
