version: 2.1

workflows:
  version: 2
  run_tests:
    jobs:
      - run_tests

jobs:
  run_tests:
    docker:
      - image: cimg/ruby:3.3.0-node
        environment:
          TZ: "America/New_York"
          RAILS_ENV: test

      - image: cimg/postgres:16.2
        environment:
          RAILS_ENV: test
          TZ: "America/New_York"
    steps:
      - checkout
      - run:
          name: make sure we have the latest bundler
          command: |
            sudo gem update --system
            gem install -f bundler:2.1.4
      - run:
          name: bundle install w/ dependent libs
          command: |
            sudo apt-get --allow-releaseinfo-change update
            sudo apt-get update
            sudo apt-get install postgresql-client libsqlite3-dev
            bundle install --path vendor/bundle
      - run:
          name: Ruby Lint
          command: bundle exec rubocop
      - run:
          name: Set up db for run
          command: |
            sudo psql -c "create role funnelcake with createdb login password 'password';" -U postgres -h localhost
            bundle exec rake db:setup
            bundle exec rake db:seed
            bundle exec rake db:migrate
      - run:
          name: Run ruby tests
          command: bundle exec rspec
