development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/blacklight-core-dev" %>
  funcake_oai_url: <%= ENV['FUNCAKE_OAI_SOLR_URL'] || "http://127.0.0.1:8090/solr/funcake_oai" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/blacklight-core-test" %>
  funcake_oai_url: <%= ENV['FUNCAKE_OAI_SOLR_URL'] || "http://127.0.0.1:8090/solr/funcake-oai" %>
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/blacklight-core" %>
  funcake_oai_url: <%= ENV['FUNCAKE_OAI_SOLR_URL'] || "http://127.0.0.1:8090/solr/funcake-oai" %>
