default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("FUNNELCAKE_DB_HOST") { "localhost" } %>
  pool: 5
  username: <%= ENV.fetch("FUNNELCAKE_DB_USER") { "funnelcake" } %>
  password: <%= ENV.fetch("FUNNELCAKE_DB_PASSWORD") { "password" }%>

development:
  <<: *default
  database: funnelcake_development

test:
  <<: *default
  database: funnelcake_test

production:
  <<: *default
  database: funnelcake_db
