name: Lint and Test

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ruby-version: ['3.4']
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: true
      matrix:
        ruby-version: ['3.4']
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Setup Postgres
        uses: ikalnytskyi/action-setup-postgres@v7
        id: postgres

      - env:
          PGSERVICE: "${{ steps.postgres.outputs.service-name }}"
        run: |
          createuser funnelcake --createdb
          psql -c "ALTER USER funnelcake WITH PASSWORD 'password'"

      - name: Setup database
        run: bundle exec rails db:setup

      - name: Run tests
        run: bundle exec rspec