name: Lint and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      TZ: America/New_York
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.3
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    needs: lint
    env:
      RAILS_ENV: test
      TZ: America/New_York
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.3
          bundler-cache: true

      - name: Setup Postgres
        uses: mullwar/setup-postgres@v2
        with:
          postgresql version: '16'
          postgresql db: postgres
          postgresql user: postgres
          postgresql password: password
          postgresql port: 5432

      - name: Create DB role
        run: |
          psql -c "create role funnelcake with createdb login password 'password';" -U postgres
          
      - name: Setup database
        run: bundle exec rails db:setup

      - name: Run tests
        run: bundle exec rspec